name: LA FABRICA DE HITS
favicon: null
layout_spectrum: 0.9279093584045768
typography_spectrum: 0.28378917812369764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8620452419854701
  lightness: 0.47950039175339043
  saturation: 0.48130539944395423
  rhythmicContrast: 0.8397506314795464
purpose: []
